#!/bin/sh
# These things are run when an Openbox X Session is started.
# You may place a similar script in $HOME/.config/openbox/autostart
# to run user-specific things.
#

# If you want to use GNOME config tools...
#
#if test -x /usr/lib/openbox/gnome-settings-daemon >/dev/null; then
#  /usr/lib/openbox/gnome-settings-daemon &
#elif which gnome-settings-daemon >/dev/null 2>&1; then
#  gnome-settings-daemon &
#fi

# If you want to use XFCE config tools...
#
#xfce-mcs-manager &
# xorg
xsetroot -cursor_name left_ptr
xset r rate 300 30
xrdb -merge ~/.Xresources

# picom
if [ "$(command -v picom)" ] &&
    [ -e "${XDG_CONFIG_HOME}/picom/picom.conf" ]; then
    picom -b --config "${XDG_CONFIG_HOME}"/picom/picom.conf &
fi
[ "$(pgrep polkit-gnome >/dev/null 2>&1)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

[ "$(command -v udiskie)" ] && udiskie -t &
[ "$(command -v iwgtk)" ] && iwgtk -i &
[ "$(command -v dunst)" ] && dunst -conf ~/.config/dunst/dunstrc &
[ -e /usr/lib/geoclue-2.0/demos/agent ] && /usr/lib/geoclue-2.0/demos/agent &
[ "$(command -v nm-applet)" ] && nm-applet &
[ "$(command -v xsettingsd)" ] && xsettingsd &
[ -e ~/.fehbg ] && ~/.fehbg &
[ "$(command -v wal)" ] && wal --theme solarized &
[ "$(command -v blueman-applet)" ] && blueman-applet &
[ "$(command -v unclutter)" ] && unclutter &
[ "$(command -v volumeicon)" ] && volumeicon &

# light-locker
[ "$(command -v light-locker)" ] && (sleep 3 && light-locker) &

# setwallpaper script
[ "$(command -v setwallpaper)" ] && (sleep 3 && setwallpaper) &
